# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3b0605e9b1911b8fb968da42b0fb20c6"
application_url = "https://shopify-webhook-ui-production.up.railway.app"
embedded = true
name = "shopfunnels-webhook-ui"
handle = "shopfunnels-webhook-ui"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

"ORDERS_CREATE" = "/webhooks/shopfunnels-order"
"CREATE_ORDER" = "/webhooks/create-order"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, write_orders, read_products, write_products"

[auth]
redirect_urls = [
  "https://shopfunnels-webhook-ui.fly.dev/auth/callback",
  "https://shopfunnels-webhook-ui.fly.dev/auth/shopify/callback",
  "https://shopfunnels-webhook-ui.fly.dev/api/auth/callback"
]

[pos]
embedded = false
